### ISSUE TITLE
Problema webservice xml

### ISSUE THREAD

**Issue by EduardJS** [dragosprotung/php2wsdl#15]
Salutare Dragoș ! Îmi cer scuze că te deranjez tocmai aici dar e singurul loc în care văd că mai ești activ! Te rog din suflet să-mi dai un mail către edi@02.ro sau să-mi raspunzi aici cu o adresă de-a ta sau orice altceva prin care să putem lua legătura în legătură cu un webservice SOAP. Ești singurul pe care l-am văzut că lucrează cu așa ceva și cu care aș putea lua legătura, bineînțeles, contra cost. Îți mulțumesc mult și poți șterge acest thread!

Cu respecte, 
Eduard!

**Comment by dragosprotung** [comment]
Ai detaliile mele in composer.json
