### ISSUE TITLE
looks like we got no XML document

### ISSUE THREAD

**Issue by Kcko** [dragosprotung/php2wsdl#21]
Hi,

with your library i generated WSDL file from simple PHP class. But when Im trying to connect to SoapServer via SoapClient i had error "looks like we got no XML document".

See github: https://github.com/Kcko/wsdl 

Can you help me? I spent a many hours on google when i tried a many solutions => WITHOUT SUCCESS.

**Comment by dragosprotung** [comment]
Yes. Also do not forget to bind something to the server.

**Comment by Kcko** [comment]
Problem solved! I had a bad implementation.

1) When we create client, URL must refer to URL where server is created.
2) In class which is handled by SoapServer must be commented by PHPDOC syntax (input params and returned result)  for example:

```
    /**
     * @soap
     * @return int
     */
    public function getDayyy()
    {
        return date('j');
    }
```

And now is fully working :-) , im happy.


One question to finish: when im creating WSDL with your class, is necessary to use "wsdl" extension? 
Its working with "xml" extension.  Or it does not matter?
```
$class = "Test";
$serviceURI = "http://localhost/cleanWSDL/server.php";
$wsdlGenerator = new PHP2WSDL\PHPClass2WSDL($class, $serviceURI);
$wsdlGenerator->generateWSDL(FALSE);
$wsdlXML = $wsdlGenerator->save('soap2.xml');
```

**Comment by dragosprotung** [comment]
Glad it works.

You can use whatever filename or extension you want. It's common to use `wsdl` to better describe what the file contains.
