### ISSUE TITLE
How to define nillable paramater

### ISSUE THREAD

**Issue by bobonov** [dragosprotung/php2wsdl#27]
How can I define nillable parameter?
I tried in several ways without success.

**Comment by mstrey** [comment]
Have you tried to use the minoccurs annotation?

https://stackoverflow.com/questions/39145464/how-specify-php2wsdl-param-cardinality

Maicon Strey
Novo Hamburgo - RS - Brasil
------------------
http://about.me/mstrey
------------------
Linux user #525086 at http://linuxcounter.net/user/525086.html


Em seg., 7 de set. de 2020 às 10:51, Roberto Braga <notifications@github.com>
escreveu:

**Comment by bobonov** [comment]
Yes tried, here is my code (maybe I've done something wrong):

Here is my soap method:
```
/**
     * @param int $id_caso
     * @param \app\controllers\SusInput $gruppo_gestione
     * @param string $descrizione_soluzione
     * @param string $stato
     * @return array
     * @soap
     */

    public function susCreate($id_caso, $gruppo_gestione=null, $descrizione_soluzione=null, $stato=null)
    {
```

This is how I defined \app\controllers\SusInput 
```
namespace app\controllers;
class SusInput
{
    /**
     * @var string
     * @nillable
     */
    public $gruppo_gestione;
}
```

And this is the result I get, instead of string as type I get tha class type="tns:app.controllers.SusInput"
```
 <message name="susCreateIn">
    <part name="id_caso" type="xsd:int"/>
    <part name="gruppo_gestione" type="tns:app.controllers.SusInput"/>
    <part name="descrizione_soluzione" type="xsd:string"/>
    <part name="stato" type="xsd:string"/>
  </message>
```

**Comment by mstrey** [comment]
have you tried this?

/**
 * @var string
 * @minOccurs 0
 */
public $gruppo_gestione;



And maybe your generated wsdl doesnt have the nillable property, but
the behaviour of minOccurs are quite the same.


Maicon Strey
Novo Hamburgo - RS - Brasil
------------------
http://about.me/mstrey
------------------
Linux user #525086 at http://linuxcounter.net/user/525086.html


Em seg., 7 de set. de 2020 às 14:38, Roberto Braga <notifications@github.com>
escreveu:

**Comment by bobonov** [comment]
I'm using the latest version of php2wsdl 0.6.1
php 7.2.18 in windows environment

>have you tried this?

Yes with minOccours the result is the same.
I made also some basic code completely outside the framework, just in case something is influencing it,  it is in the following zip.
The file is with @minOccurs 0 exactly like the example on stackoverflow

[test.zip](https://github.com/dragosprotung/php2wsdl/files/5184816/test.zip)

but the result is still wrong
```xml
<message name="soapCallIn">
    <part name="first" type="xsd:int"/>
    <part name="second" type="xsd:string"/>
    <part name="third" type="tns:test.TestInput"/>
</message>
```

**Comment by mstrey** [comment]
well, i take the problem with minOccurs. my mistake. it only works with
arrays.
so, for your pourpose should work if you just use @nillable, like the code
below:

/**
 * @var string
 * @nillable
 */
public $gruppo_gestione;

you can check this on the file of the lib:
https://github.com/dragosprotung/php2wsdl/blob/master/src/WSDL.php
on line 437 it has that IF to check the nillable annotation.

but looks like you are looking to the wrong element on the WSDL.
you are setting up as nillable a parameter of SusInput, but you are
checking the nillable property of SusCreateIn parameter.

If you want the entyre SusInput are nillable try create a single input
element with all parameters. something like that:
 /**

     * @param susCreateInput $input
     * @return array
     * @soap
     */

    public function susCreate($input)
    {


class susCreateInput(

    /**   * @var int $id_caso     */    public $id_caso

    /**     * @var \app\controllers\SusInput $sus_input     *
@nillable     */    public $sus_input

    /**     * @var string $descrizione_soluzione     * @nillable
*/    public $descrizione_soluzione

    /**     * @var string $stato     * @nillable     */    public $stato

}
class SusInput

{    /**
     * @var string
     * @nillable
     */
    public $gruppo_gestione;
}


To be clear:
@nillable is a annotation only for @var, not for @parameter

I hope it will help you.

Maicon Strey
Novo Hamburgo - RS - Brasil
------------------
http://about.me/mstrey
------------------
Linux user #525086 at http://linuxcounter.net/user/525086.html


Em seg., 7 de set. de 2020 às 17:20, Roberto Braga <notifications@github.com>
escreveu:

**Comment by bobonov** [comment]
Sorry for late answer, I was in hurry to finish the work. Defining an external class to define the data worked as expected, thanks
