### ISSUE TITLE
php 8.0.3 yields fatal error in getConstants()

### ISSUE THREAD

**Issue by ekrellw** [dragosprotung/php2wsdl#28]
I am trying to use this package with php 8.0.3 and I get the following fatal error:

PHP Fatal error:  Declaration of Wingu\OctopusCore\Reflection\ReflectionClass::getConstants() must be compatible with ReflectionClass::getConstants(?int $filter = null) in /var/www/html/php2wsdl-2019-10-17/vendor/wingu/reflection/src/ReflectionClass.php on line 234

probably due to stricter type checking in php.

**Comment by cris-m** [comment]
Is there any fix for this issue? I am getting this issue in ``php  8.0.2``. Running the project in ``php 7.4.15``, I am getting the different.
```
Uncaught ReflectionException: Class $string does not exist in ... /vendor/php2wsdl/php2wsdl/src/WSDL.php:422
```

**Comment by ekrellw** [comment]
I have not get a answer. SORRY
I am use nusoap to create wsdl file with php 8.0.3

**Comment by zorn-v** [comment]
> Is there any fix for this issue? I am getting this issue in `php 8.0.2`. Running the project in `php 7.4.15`, I am getting the different.
> 
> ```
> Uncaught ReflectionException: Class $string does not exist in ... /vendor/php2wsdl/php2wsdl/src/WSDL.php:422
> ```

Seems you just write wrong docblock for method. Something like `@param $string $arg1` and of course class/type `$string` does not exists

**Comment by ekrellw** [comment]
I never got an answer so I decided to drop this library from my project and
I use now Wsdlphp which runs in one program both the WSDL generator and a
html description of the  service

**Comment by dragosprotung** [comment]
Fixed after merging https://github.com/Speicher210/Reflection/pull/4
