### ISSUE TITLE
Style sheet missing

### ISSUE THREAD

**Issue by farazilu** [dragosprotung/php2wsdl#8]
Hi, can you add following WSDL style sheet http://tomi.vanek.sk/index.php?page=wsdl-viewer
its really good

**Comment by dragosprotung** [comment]
I think a better solution would be to allow setting an xsl to the generated WSDL.

Hard coding a specific style sheet is not a good idea.

Also, the sheet you are proposing is under the Apache license. Adding it would mean to change the licence for this package.

**Comment by farazilu** [comment]
If you can do that that will be the best solution.

**Comment by farazilu** [comment]
I managed to achieve this by updating WSDL class and adding following lines in constructor, you can create a function to set this value.
	$xslt = $this->dom->createProcessingInstruction('xml-stylesheet', 'type="text/xsl" href="/css/wsdl-viewer.xsl"');
	$this->dom->appendChild($xslt);

**Comment by dragosprotung** [comment]
I will try to add it in the next days. If you want you can open a PR for this (with tests) and i will be happy to merge it. But the XSL link should not be in constructor, but a simple setter function
