### ISSUE TITLE
Missing Type

### ISSUE THREAD

**Issue by matias-yii** [dragosprotung/php2wsdl#9]
Could you please add decimal type to  static $XSDTypes. Thanks.

**Comment by matias-yii** [comment]
I made a pull request with the change.

**Comment by dragosprotung** [comment]
Can you add one test for it ? I will merge it after that. Thanks

**Comment by matias-yii** [comment]
Sure, but I don't know what kind of test? I only added this line 'decimal'=>'xsd:decimal. Thanks.

**Comment by matias-yii** [comment]
I think is done.

**Comment by dragosprotung** [comment]
I merged the pull request and i will add the tests myself.

**Comment by matias-yii** [comment]
great. Thanks!!!
